[advisories]
ignore = []
informational_warnings = ["unmaintained"]
severity_threshold = "low"

# Advisory Database Configuration
[database]
path = "~/.cargo/advisory-db"
url = "https://github.com/RustSec/advisory-db.git"
fetch = true
stale = false

# Output Configuration
[output]
deny = ["unmaintained"]
format = "terminal"
quiet = false
show_tree = true

# Target Configuration
[target]
arch = ["x86_64"]
os = ["linux"]

[yanked]
enabled = true
update_index = true
